SET
  SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";

START TRANSACTION;

SET
  time_zone = "+00:00";

CREATE TABLE `pokemon` (
  `_id` int(11) NOT NULL,
  `name` varchar(100) NOT NULL,
  `url` varchar(300)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

INSERT INTO
  `pokemon` (`_id`, `name`, `url`)
VALUES
  (1, "bulbasaur", NULL),
  (2, "ivysaur", NULL),
  (3, "venusaur", NULL),
  (4, "charmander", NULL),
  (5, "charmeleon", NULL),
  (6, "charizard", NULL),
  (7, "squirtle", NULL),
  (8, "wartortle", NULL),
  (9, "blastoise", NULL),
  (10, "caterpie", NULL),
  (11, "metapod", NULL),
  (12, "butterfree", NULL),
  (13, "weedle", NULL),
  (14, "kakuna", NULL),
  (15, "beedrill", NULL),
  (16, "pidgey", NULL),
  (17, "pidgeotto", NULL),
  (18, "pidgeot", NULL),
  (19, "rattata", NULL),
  (20, "raticate", NULL),
  (21, "spearow", NULL),
  (22, "fearow", NULL),
  (23, "ekans", NULL),
  (24, "arbok", NULL),
  (25, "pikachu", 'https://wallpapers-clan.com/wp-content/uploads/2023/11/cute-pokemon-pikachu-rain-desktop-wallpaper-preview.jpg'),
  (26, "raichu", NULL),
  (27, "sandshrew", NULL),
  (28, "sandslash", NULL),
  (29, "nidoran-f", NULL),
  (30, "nidorina", NULL),
  (31, "nidoqueen", NULL),
  (32, "nidoran-m", NULL),
  (33, "nidorino", NULL),
  (34, "nidoking", NULL),
  (35, "clefairy", NULL),
  (36, "clefable", NULL),
  (37, "vulpix", NULL),
  (38, "ninetales", NULL),
  (39, "jigglypuff", NULL),
  (40, "wigglytuff", NULL),
  (41, "zubat", NULL),
  (42, "golbat", NULL),
  (43, "oddish", NULL),
  (44, "gloom", NULL),
  (45, "vileplume", NULL),
  (46, "paras", NULL),
  (47, "parasect", NULL),
  (48, "venonat", NULL),
  (49, "venomoth", NULL),
  (50, "diglett", NULL),
  (51, "dugtrio", NULL),
  (52, "meowth", NULL),
  (53, "persian", NULL),
  (54, "psyduck", NULL),
  (55, "golduck", NULL),
  (56, "mankey", NULL),
  (57, "primeape", NULL),
  (58, "growlithe", NULL),
  (59, "arcanine", NULL),
  (60, "poliwag", NULL),
  (61, "poliwhirl", NULL),
  (62, "poliwrath", NULL),
  (63, "abra", NULL),
  (64, "kadabra", NULL),
  (65, "alakazam", NULL),
  (66, "machop", NULL),
  (67, "machoke", NULL),
  (68, "machamp", NULL),
  (69, "bellsprout", NULL),
  (70, "weepinbell", NULL),
  (71, "victreebel", NULL),
  (72, "tentacool", NULL),
  (73, "tentacruel", NULL),
  (74, "geodude", NULL),
  (75, "graveler", NULL),
  (76, "golem", NULL),
  (77, "ponyta", NULL),
  (78, "rapidash", NULL),
  (79, "slowpoke", NULL),
  (80, "slowbro", NULL),
  (81, "magnemite", NULL),
  (82, "magneton", NULL),
  (83, "farfetchd", NULL),
  (84, "doduo", NULL),
  (85, "dodrio", NULL),
  (86, "seel", NULL),
  (87, "dewgong", NULL),
  (88, "grimer", NULL),
  (89, "muk", NULL),
  (90, "shellder", NULL),
  (91, "cloyster", NULL),
  (92, "gastly", NULL),
  (93, "haunter", NULL),
  (94, "gengar", 'https://wallpapers-clan.com/wp-content/uploads/2024/04/pokemon-gengar-cool-red-desktop-wallpaper-preview.jpg'),
  (95, "onix", NULL),
  (96, "drowzee", NULL),
  (97, "hypno", NULL),
  (98, "krabby", NULL),
  (99, "kingler", NULL),
  (100, "voltorb", NULL),
  (101, "electrode", NULL),
  (102, "exeggcute", NULL),
  (103, "exeggutor", NULL),
  (104, "cubone", NULL),
  (105, "marowak", NULL),
  (106, "hitmonlee", NULL),
  (107, "hitmonchan", NULL),
  (108, "lickitung", NULL),
  (109, "koffing", NULL),
  (110, "weezing", NULL),
  (111, "rhyhorn", NULL),
  (112, "rhydon", NULL),
  (113, "chansey", NULL),
  (114, "tangela", NULL),
  (115, "kangaskhan", NULL),
  (116, "horsea", NULL),
  (117, "seadra", NULL),
  (118, "goldeen", NULL),
  (119, "seaking", NULL),
  (120, "staryu", NULL),
  (121, "starmie", NULL),
  (122, "mr-mime", NULL),
  (123, "scyther", NULL),
  (124, "jynx", NULL),
  (125, "electabuzz", NULL),
  (126, "magmar", NULL),
  (127, "pinsir", NULL),
  (128, "tauros", NULL),
  (129, "magikarp", NULL),
  (130, "gyarados", NULL),
  (131, "lapras", NULL),
  (132, "ditto", NULL),
  (133, "eevee", NULL),
  (134, "vaporeon", NULL),
  (135, "jolteon", NULL),
  (136, "flareon", NULL),
  (137, "porygon", NULL),
  (138, "omanyte", NULL),
  (139, "omastar", NULL),
  (140, "kabuto", NULL),
  (141, "kabutops", NULL),
  (142, "aerodactyl", NULL),
  (143, "snorlax", NULL),
  (144, "articuno", NULL),
  (145, "zapdos", NULL),
  (146, "moltres", NULL),
  (147, "dratini", NULL),
  (148, "dragonair", NULL),
  (149, "dragonite", NULL),
  (150, "mewtwo", 'https://wallpapers-clan.com/wp-content/uploads/2024/04/aesthetic-pokemon-mewtwo-desktop-wallpaper-preview.jpg'),
  (151, "mew", NULL);

CREATE TABLE `user` (
  `_id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `name` varchar(50) NOT NULL,
  `email` varchar(50) NOT NULL,
  `password` varchar(255) NOT NULL,
  `clearence` varchar(100) NOT NULL
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

INSERT INTO
  `user` (`_id`, `name`, `email`, `password`, `clearence`)
VALUES
  (
    1,
    'GASPI',
    'gaspi.tudai@gmail.com',
    '$2y$10$d/AcpkdKVEeHr7Cd/uAM/.EYA86EsjR/Noy/avzyB4UkpztWlCuYq',
    'admin'
  ),
  (
    2,
    'LAUTA',
    'lauta@lauta.com',
    '$2y$10$8Xt2oAL8ZazAXNS5bQxT5eA9lT.myDGgHRrt41BcytlPlqdWvuXHW',
    'admin'
  ),
  COMMIT;